### ISSUE TITLE
DVC pipeline visualization

### ISSUE THREAD

**Issue by simonlsk** [drostlab/network-inference-pipeline#1]
Hey, this is a really cool project. I was looking for projects with interesting dvc pipelines and found yours. I was wondering if you heard about DagsHub? It’s like GitHub for data science built on top of Git + DVC. I connected your project and you can check out the interactive pipeline [here](https://dagshub.com/Simon/network-inference-pipeline
). Would be happy to transfer project ownership if you want.

![image](https://user-images.githubusercontent.com/28020880/134355869-bf14e95c-ecdd-4342-90e4-f2d8dfc27fe0.png)

**Comment by lmshk** [comment]
Thank you for your interest. Currently, plain `dvc` is sufficient for us, but we will consider your software if we have a more complex workflow in the future.
