### ISSUE TITLE
load_genie3r_network.function.R: column order != row order if nCores > 1

### ISSUE THREAD

**Issue by aciobanusebi** [drostlab/network-inference-pipeline#2]
I would have a suggestion. Could you change src/analysis/load_genie3r_network.function.R to

```
function(filename) {
  result <- as.matrix(read.csv(filename, row.names = 1))
  result <- result[rownames(result),rownames(result)]
  result
}
```

since for the network inference I changed src/inference/GENIE3-R/infer_network.R into:
```
arguments <- commandArgs(trailingOnly = TRUE)
input_filename <- arguments[1]
output_filename <- arguments[2]

write.csv(
  GENIE3::GENIE3(
    as.matrix(
      read.csv(input_filename, row.names = 1)
    ),
   nCores = 31   # THE CHANGE
  ),
  file = output_filename
)

```
and obtained a different order of columns/rows?

Perhaps, this problem does not exist if you use your code (i.e. with nCores=1), but if users like me change that parameter some errors may occur (and occurred in my case) in the pipeline.

**Comment by lmshk** [comment]
Thanks for your feedback. I changed this with [e4f20ff4](https://github.com/drostlab/network-inference-pipeline/commit/e4f20ff416b2036228eeacf519488424711ffe1f).
